name: Checking

on:
  push
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/check.yml'

jobs:
  check:
    name: Finding suspicious constructs for ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: mipsle
            gomips: softfloat
          - goos: linux
            goarch: mips
            gomips: softfloat
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Finding suspicious constructs
        working-directory: ./src/backend
        run: |
          GOOS="${{ matrix.goos }}" GOARCH="${{ matrix.goarch }}" GOMIPS="${{ matrix.gomips }}" GOARM="${{ matrix.goarm }}" go vet ./...

  test_backend:
    name: Backend testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Backend tests
        working-directory: ./src/backend
        run: |
          GOOS=linux go test ./...

      - name: Install netfilter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iptables ipset iproute2

      - name: Backend routing e2e
        working-directory: ./src/backend
        env:
          NETFILTER_TESTS: "1"
        run: |
          sudo -E env "PATH=$PATH" GOOS=linux go test -run TestRoutingE2E ./tests/...

  test_frontend:
    name: Frontend testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Install frontend dependencies
        working-directory: ./src/frontend
        run: npm install

      - name: Install Playwright browsers
        working-directory: ./src/frontend
        run: npx playwright install --with-deps

      - name: Frontend unit tests
        working-directory: ./src/frontend
        run: npm run test:unit

      - name: Frontend e2e tests
        working-directory: ./src/frontend
        run: npm run test:e2e
